---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[s3_dir_test::default]
