---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: ami-190e4b73
    tags:
      Name: s3_dir-default-ubuntu-1204
- name: ubuntu-14.04
  driver_config:
    image_id: ami-9883c6f2
    tags:
      Name: s3_dir-default-ubuntu-1404

suites:
- name: default
  run_list:
      - recipe[apt]
      - recipe[s3_dir_test::default]
