Documentation:
  Enabled: false

# Disable encoding requirement
Encoding:
  Enabled: false

# The default 79 character limit is sometimes unproductive.
LineLength:
  Max: 100

# The default 10 lines limit is unrealistic.
MethodLength:
  Max: 50

CyclomaticComplexity:
  Max: 10

# Advantageous for readability to line up attributes
SingleSpaceBeforeFirstArg:
  Enabled: false

AbcSize:
  Enabled: false
